version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CLIENT_ID=<CLIENT_ID>
      - CLIENT_SECRET=<CLIENT_SECRET>
    volumes:
      - ./app:/app

    network_mode: "host"